// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/gpmc/v1/messages.proto

package gpmcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUploadTokenRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_F1       int32                  `protobuf:"varint,1,opt,name=f1,proto3"`
	xxx_hidden_F2       int32                  `protobuf:"varint,2,opt,name=f2,proto3"`
	xxx_hidden_F3       int32                  `protobuf:"varint,3,opt,name=f3,proto3"`
	xxx_hidden_F4       int32                  `protobuf:"varint,4,opt,name=f4,proto3"`
	xxx_hidden_FileSize int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetUploadTokenRequest) Reset() {
	*x = GetUploadTokenRequest{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadTokenRequest) ProtoMessage() {}

func (x *GetUploadTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetUploadTokenRequest) GetF1() int32 {
	if x != nil {
		return x.xxx_hidden_F1
	}
	return 0
}

func (x *GetUploadTokenRequest) GetF2() int32 {
	if x != nil {
		return x.xxx_hidden_F2
	}
	return 0
}

func (x *GetUploadTokenRequest) GetF3() int32 {
	if x != nil {
		return x.xxx_hidden_F3
	}
	return 0
}

func (x *GetUploadTokenRequest) GetF4() int32 {
	if x != nil {
		return x.xxx_hidden_F4
	}
	return 0
}

func (x *GetUploadTokenRequest) GetFileSize() int64 {
	if x != nil {
		return x.xxx_hidden_FileSize
	}
	return 0
}

func (x *GetUploadTokenRequest) SetF1(v int32) {
	x.xxx_hidden_F1 = v
}

func (x *GetUploadTokenRequest) SetF2(v int32) {
	x.xxx_hidden_F2 = v
}

func (x *GetUploadTokenRequest) SetF3(v int32) {
	x.xxx_hidden_F3 = v
}

func (x *GetUploadTokenRequest) SetF4(v int32) {
	x.xxx_hidden_F4 = v
}

func (x *GetUploadTokenRequest) SetFileSize(v int64) {
	x.xxx_hidden_FileSize = v
}

type GetUploadTokenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	F1       int32
	F2       int32
	F3       int32
	F4       int32
	FileSize int64
}

func (b0 GetUploadTokenRequest_builder) Build() *GetUploadTokenRequest {
	m0 := &GetUploadTokenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_F1 = b.F1
	x.xxx_hidden_F2 = b.F2
	x.xxx_hidden_F3 = b.F3
	x.xxx_hidden_F4 = b.F4
	x.xxx_hidden_FileSize = b.FileSize
	return m0
}

type FindRemoteMediaByHashRequest struct {
	state            protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_Inner *FindRemoteMediaByHashRequest_Inner `protobuf:"bytes,1,opt,name=inner,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindRemoteMediaByHashRequest) Reset() {
	*x = FindRemoteMediaByHashRequest{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRemoteMediaByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRemoteMediaByHashRequest) ProtoMessage() {}

func (x *FindRemoteMediaByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FindRemoteMediaByHashRequest) GetInner() *FindRemoteMediaByHashRequest_Inner {
	if x != nil {
		return x.xxx_hidden_Inner
	}
	return nil
}

func (x *FindRemoteMediaByHashRequest) SetInner(v *FindRemoteMediaByHashRequest_Inner) {
	x.xxx_hidden_Inner = v
}

func (x *FindRemoteMediaByHashRequest) HasInner() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Inner != nil
}

func (x *FindRemoteMediaByHashRequest) ClearInner() {
	x.xxx_hidden_Inner = nil
}

type FindRemoteMediaByHashRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Inner *FindRemoteMediaByHashRequest_Inner
}

func (b0 FindRemoteMediaByHashRequest_builder) Build() *FindRemoteMediaByHashRequest {
	m0 := &FindRemoteMediaByHashRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Inner = b.Inner
	return m0
}

type FindRemoteMediaByHashResponse struct {
	state         protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_L1 *FindRemoteMediaByHashResponse_L1 `protobuf:"bytes,1,opt,name=l1,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRemoteMediaByHashResponse) Reset() {
	*x = FindRemoteMediaByHashResponse{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRemoteMediaByHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRemoteMediaByHashResponse) ProtoMessage() {}

func (x *FindRemoteMediaByHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FindRemoteMediaByHashResponse) GetL1() *FindRemoteMediaByHashResponse_L1 {
	if x != nil {
		return x.xxx_hidden_L1
	}
	return nil
}

func (x *FindRemoteMediaByHashResponse) SetL1(v *FindRemoteMediaByHashResponse_L1) {
	x.xxx_hidden_L1 = v
}

func (x *FindRemoteMediaByHashResponse) HasL1() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_L1 != nil
}

func (x *FindRemoteMediaByHashResponse) ClearL1() {
	x.xxx_hidden_L1 = nil
}

type FindRemoteMediaByHashResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	L1 *FindRemoteMediaByHashResponse_L1
}

func (b0 FindRemoteMediaByHashResponse_builder) Build() *FindRemoteMediaByHashResponse {
	m0 := &FindRemoteMediaByHashResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_L1 = b.L1
	return m0
}

type UploadReceipt struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Field1 int64                  `protobuf:"varint,1,opt,name=field1,proto3"`
	xxx_hidden_Field2 []byte                 `protobuf:"bytes,2,opt,name=field2,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UploadReceipt) Reset() {
	*x = UploadReceipt{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReceipt) ProtoMessage() {}

func (x *UploadReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadReceipt) GetField1() int64 {
	if x != nil {
		return x.xxx_hidden_Field1
	}
	return 0
}

func (x *UploadReceipt) GetField2() []byte {
	if x != nil {
		return x.xxx_hidden_Field2
	}
	return nil
}

func (x *UploadReceipt) SetField1(v int64) {
	x.xxx_hidden_Field1 = v
}

func (x *UploadReceipt) SetField2(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Field2 = v
}

type UploadReceipt_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Field1 int64
	Field2 []byte
}

func (b0 UploadReceipt_builder) Build() *UploadReceipt {
	m0 := &UploadReceipt{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Field1 = b.Field1
	x.xxx_hidden_Field2 = b.Field2
	return m0
}

type CommitUploadRequest struct {
	state              protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Inner   *CommitUploadRequest_Inner  `protobuf:"bytes,1,opt,name=inner,proto3"`
	xxx_hidden_Device  *CommitUploadRequest_Device `protobuf:"bytes,2,opt,name=device,proto3"`
	xxx_hidden_Trailer []byte                      `protobuf:"bytes,3,opt,name=trailer,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CommitUploadRequest) Reset() {
	*x = CommitUploadRequest{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadRequest) ProtoMessage() {}

func (x *CommitUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommitUploadRequest) GetInner() *CommitUploadRequest_Inner {
	if x != nil {
		return x.xxx_hidden_Inner
	}
	return nil
}

func (x *CommitUploadRequest) GetDevice() *CommitUploadRequest_Device {
	if x != nil {
		return x.xxx_hidden_Device
	}
	return nil
}

func (x *CommitUploadRequest) GetTrailer() []byte {
	if x != nil {
		return x.xxx_hidden_Trailer
	}
	return nil
}

func (x *CommitUploadRequest) SetInner(v *CommitUploadRequest_Inner) {
	x.xxx_hidden_Inner = v
}

func (x *CommitUploadRequest) SetDevice(v *CommitUploadRequest_Device) {
	x.xxx_hidden_Device = v
}

func (x *CommitUploadRequest) SetTrailer(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Trailer = v
}

func (x *CommitUploadRequest) HasInner() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Inner != nil
}

func (x *CommitUploadRequest) HasDevice() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Device != nil
}

func (x *CommitUploadRequest) ClearInner() {
	x.xxx_hidden_Inner = nil
}

func (x *CommitUploadRequest) ClearDevice() {
	x.xxx_hidden_Device = nil
}

type CommitUploadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Inner   *CommitUploadRequest_Inner
	Device  *CommitUploadRequest_Device
	Trailer []byte
}

func (b0 CommitUploadRequest_builder) Build() *CommitUploadRequest {
	m0 := &CommitUploadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Inner = b.Inner
	x.xxx_hidden_Device = b.Device
	x.xxx_hidden_Trailer = b.Trailer
	return m0
}

type CommitUploadResponse struct {
	state         protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_L1 *CommitUploadResponse_L1 `protobuf:"bytes,1,opt,name=l1,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadResponse) Reset() {
	*x = CommitUploadResponse{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadResponse) ProtoMessage() {}

func (x *CommitUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommitUploadResponse) GetL1() *CommitUploadResponse_L1 {
	if x != nil {
		return x.xxx_hidden_L1
	}
	return nil
}

func (x *CommitUploadResponse) SetL1(v *CommitUploadResponse_L1) {
	x.xxx_hidden_L1 = v
}

func (x *CommitUploadResponse) HasL1() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_L1 != nil
}

func (x *CommitUploadResponse) ClearL1() {
	x.xxx_hidden_L1 = nil
}

type CommitUploadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	L1 *CommitUploadResponse_L1
}

func (b0 CommitUploadResponse_builder) Build() *CommitUploadResponse {
	m0 := &CommitUploadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_L1 = b.L1
	return m0
}

type PrepareDownloadRequest struct {
	state             protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Key    *PrepareDownloadRequest_KeyOuter `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_Opaque *PrepareDownloadRequest_Opaque   `protobuf:"bytes,2,opt,name=opaque,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrepareDownloadRequest) Reset() {
	*x = PrepareDownloadRequest{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadRequest) ProtoMessage() {}

func (x *PrepareDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadRequest) GetKey() *PrepareDownloadRequest_KeyOuter {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *PrepareDownloadRequest) GetOpaque() *PrepareDownloadRequest_Opaque {
	if x != nil {
		return x.xxx_hidden_Opaque
	}
	return nil
}

func (x *PrepareDownloadRequest) SetKey(v *PrepareDownloadRequest_KeyOuter) {
	x.xxx_hidden_Key = v
}

func (x *PrepareDownloadRequest) SetOpaque(v *PrepareDownloadRequest_Opaque) {
	x.xxx_hidden_Opaque = v
}

func (x *PrepareDownloadRequest) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *PrepareDownloadRequest) HasOpaque() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Opaque != nil
}

func (x *PrepareDownloadRequest) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *PrepareDownloadRequest) ClearOpaque() {
	x.xxx_hidden_Opaque = nil
}

type PrepareDownloadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key    *PrepareDownloadRequest_KeyOuter
	Opaque *PrepareDownloadRequest_Opaque
}

func (b0 PrepareDownloadRequest_builder) Build() *PrepareDownloadRequest {
	m0 := &PrepareDownloadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Opaque = b.Opaque
	return m0
}

type LibStateRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Inner *LibStateRequest_Inner `protobuf:"bytes,1,opt,name=inner,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LibStateRequest) Reset() {
	*x = LibStateRequest{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibStateRequest) ProtoMessage() {}

func (x *LibStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LibStateRequest) GetInner() *LibStateRequest_Inner {
	if x != nil {
		return x.xxx_hidden_Inner
	}
	return nil
}

func (x *LibStateRequest) SetInner(v *LibStateRequest_Inner) {
	x.xxx_hidden_Inner = v
}

func (x *LibStateRequest) HasInner() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Inner != nil
}

func (x *LibStateRequest) ClearInner() {
	x.xxx_hidden_Inner = nil
}

type LibStateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Inner *LibStateRequest_Inner
}

func (b0 LibStateRequest_builder) Build() *LibStateRequest {
	m0 := &LibStateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Inner = b.Inner
	return m0
}

type LibStateResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Body *LibStateResponse_Body `protobuf:"bytes,1,opt,name=body,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LibStateResponse) Reset() {
	*x = LibStateResponse{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibStateResponse) ProtoMessage() {}

func (x *LibStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LibStateResponse) GetBody() *LibStateResponse_Body {
	if x != nil {
		return x.xxx_hidden_Body
	}
	return nil
}

func (x *LibStateResponse) SetBody(v *LibStateResponse_Body) {
	x.xxx_hidden_Body = v
}

func (x *LibStateResponse) HasBody() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Body != nil
}

func (x *LibStateResponse) ClearBody() {
	x.xxx_hidden_Body = nil
}

type LibStateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Body *LibStateResponse_Body
}

func (b0 LibStateResponse_builder) Build() *LibStateResponse {
	m0 := &LibStateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Body = b.Body
	return m0
}

type MediaItem struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MediaKey string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3"`
	xxx_hidden_Meta     *MediaItem_Meta        `protobuf:"bytes,2,opt,name=meta,proto3"`
	xxx_hidden_Kind     *MediaItem_Kind        `protobuf:"bytes,5,opt,name=kind,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MediaItem) Reset() {
	*x = MediaItem{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem) ProtoMessage() {}

func (x *MediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaItem) GetMediaKey() string {
	if x != nil {
		return x.xxx_hidden_MediaKey
	}
	return ""
}

func (x *MediaItem) GetMeta() *MediaItem_Meta {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *MediaItem) GetKind() *MediaItem_Kind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return nil
}

func (x *MediaItem) SetMediaKey(v string) {
	x.xxx_hidden_MediaKey = v
}

func (x *MediaItem) SetMeta(v *MediaItem_Meta) {
	x.xxx_hidden_Meta = v
}

func (x *MediaItem) SetKind(v *MediaItem_Kind) {
	x.xxx_hidden_Kind = v
}

func (x *MediaItem) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Meta != nil
}

func (x *MediaItem) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *MediaItem) ClearMeta() {
	x.xxx_hidden_Meta = nil
}

func (x *MediaItem) ClearKind() {
	x.xxx_hidden_Kind = nil
}

type MediaItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MediaKey string
	Meta     *MediaItem_Meta
	Kind     *MediaItem_Kind
}

func (b0 MediaItem_builder) Build() *MediaItem {
	m0 := &MediaItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MediaKey = b.MediaKey
	x.xxx_hidden_Meta = b.Meta
	x.xxx_hidden_Kind = b.Kind
	return m0
}

type PrepareDownloadResponse struct {
	state         protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_L1 *PrepareDownloadResponse_L1 `protobuf:"bytes,1,opt,name=l1,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDownloadResponse) Reset() {
	*x = PrepareDownloadResponse{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadResponse) ProtoMessage() {}

func (x *PrepareDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadResponse) GetL1() *PrepareDownloadResponse_L1 {
	if x != nil {
		return x.xxx_hidden_L1
	}
	return nil
}

func (x *PrepareDownloadResponse) SetL1(v *PrepareDownloadResponse_L1) {
	x.xxx_hidden_L1 = v
}

func (x *PrepareDownloadResponse) HasL1() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_L1 != nil
}

func (x *PrepareDownloadResponse) ClearL1() {
	x.xxx_hidden_L1 = nil
}

type PrepareDownloadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	L1 *PrepareDownloadResponse_L1
}

func (b0 PrepareDownloadResponse_builder) Build() *PrepareDownloadResponse {
	m0 := &PrepareDownloadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_L1 = b.L1
	return m0
}

type FindRemoteMediaByHashRequest_Inner struct {
	state             protoimpl.MessageState                    `protogen:"opaque.v1"`
	xxx_hidden_Hash   *FindRemoteMediaByHashRequest_Inner_Hash  `protobuf:"bytes,1,opt,name=hash,proto3"`
	xxx_hidden_Marker *FindRemoteMediaByHashRequest_Inner_Empty `protobuf:"bytes,2,opt,name=marker,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FindRemoteMediaByHashRequest_Inner) Reset() {
	*x = FindRemoteMediaByHashRequest_Inner{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRemoteMediaByHashRequest_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRemoteMediaByHashRequest_Inner) ProtoMessage() {}

func (x *FindRemoteMediaByHashRequest_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FindRemoteMediaByHashRequest_Inner) GetHash() *FindRemoteMediaByHashRequest_Inner_Hash {
	if x != nil {
		return x.xxx_hidden_Hash
	}
	return nil
}

func (x *FindRemoteMediaByHashRequest_Inner) GetMarker() *FindRemoteMediaByHashRequest_Inner_Empty {
	if x != nil {
		return x.xxx_hidden_Marker
	}
	return nil
}

func (x *FindRemoteMediaByHashRequest_Inner) SetHash(v *FindRemoteMediaByHashRequest_Inner_Hash) {
	x.xxx_hidden_Hash = v
}

func (x *FindRemoteMediaByHashRequest_Inner) SetMarker(v *FindRemoteMediaByHashRequest_Inner_Empty) {
	x.xxx_hidden_Marker = v
}

func (x *FindRemoteMediaByHashRequest_Inner) HasHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Hash != nil
}

func (x *FindRemoteMediaByHashRequest_Inner) HasMarker() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Marker != nil
}

func (x *FindRemoteMediaByHashRequest_Inner) ClearHash() {
	x.xxx_hidden_Hash = nil
}

func (x *FindRemoteMediaByHashRequest_Inner) ClearMarker() {
	x.xxx_hidden_Marker = nil
}

type FindRemoteMediaByHashRequest_Inner_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Hash   *FindRemoteMediaByHashRequest_Inner_Hash
	Marker *FindRemoteMediaByHashRequest_Inner_Empty
}

func (b0 FindRemoteMediaByHashRequest_Inner_builder) Build() *FindRemoteMediaByHashRequest_Inner {
	m0 := &FindRemoteMediaByHashRequest_Inner{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Hash = b.Hash
	x.xxx_hidden_Marker = b.Marker
	return m0
}

type FindRemoteMediaByHashRequest_Inner_Hash struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sha1 []byte                 `protobuf:"bytes,1,opt,name=sha1,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindRemoteMediaByHashRequest_Inner_Hash) Reset() {
	*x = FindRemoteMediaByHashRequest_Inner_Hash{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRemoteMediaByHashRequest_Inner_Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRemoteMediaByHashRequest_Inner_Hash) ProtoMessage() {}

func (x *FindRemoteMediaByHashRequest_Inner_Hash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FindRemoteMediaByHashRequest_Inner_Hash) GetSha1() []byte {
	if x != nil {
		return x.xxx_hidden_Sha1
	}
	return nil
}

func (x *FindRemoteMediaByHashRequest_Inner_Hash) SetSha1(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Sha1 = v
}

type FindRemoteMediaByHashRequest_Inner_Hash_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sha1 []byte
}

func (b0 FindRemoteMediaByHashRequest_Inner_Hash_builder) Build() *FindRemoteMediaByHashRequest_Inner_Hash {
	m0 := &FindRemoteMediaByHashRequest_Inner_Hash{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sha1 = b.Sha1
	return m0
}

type FindRemoteMediaByHashRequest_Inner_Empty struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRemoteMediaByHashRequest_Inner_Empty) Reset() {
	*x = FindRemoteMediaByHashRequest_Inner_Empty{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRemoteMediaByHashRequest_Inner_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRemoteMediaByHashRequest_Inner_Empty) ProtoMessage() {}

func (x *FindRemoteMediaByHashRequest_Inner_Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FindRemoteMediaByHashRequest_Inner_Empty_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 FindRemoteMediaByHashRequest_Inner_Empty_builder) Build() *FindRemoteMediaByHashRequest_Inner_Empty {
	m0 := &FindRemoteMediaByHashRequest_Inner_Empty{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type FindRemoteMediaByHashResponse_L1 struct {
	state         protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_L2 *FindRemoteMediaByHashResponse_L1_L2 `protobuf:"bytes,2,opt,name=l2,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRemoteMediaByHashResponse_L1) Reset() {
	*x = FindRemoteMediaByHashResponse_L1{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRemoteMediaByHashResponse_L1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRemoteMediaByHashResponse_L1) ProtoMessage() {}

func (x *FindRemoteMediaByHashResponse_L1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FindRemoteMediaByHashResponse_L1) GetL2() *FindRemoteMediaByHashResponse_L1_L2 {
	if x != nil {
		return x.xxx_hidden_L2
	}
	return nil
}

func (x *FindRemoteMediaByHashResponse_L1) SetL2(v *FindRemoteMediaByHashResponse_L1_L2) {
	x.xxx_hidden_L2 = v
}

func (x *FindRemoteMediaByHashResponse_L1) HasL2() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_L2 != nil
}

func (x *FindRemoteMediaByHashResponse_L1) ClearL2() {
	x.xxx_hidden_L2 = nil
}

type FindRemoteMediaByHashResponse_L1_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	L2 *FindRemoteMediaByHashResponse_L1_L2
}

func (b0 FindRemoteMediaByHashResponse_L1_builder) Build() *FindRemoteMediaByHashResponse_L1 {
	m0 := &FindRemoteMediaByHashResponse_L1{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_L2 = b.L2
	return m0
}

type FindRemoteMediaByHashResponse_L1_L2 struct {
	state         protoimpl.MessageState                  `protogen:"opaque.v1"`
	xxx_hidden_L3 *FindRemoteMediaByHashResponse_L1_L2_L3 `protobuf:"bytes,2,opt,name=l3,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRemoteMediaByHashResponse_L1_L2) Reset() {
	*x = FindRemoteMediaByHashResponse_L1_L2{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRemoteMediaByHashResponse_L1_L2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRemoteMediaByHashResponse_L1_L2) ProtoMessage() {}

func (x *FindRemoteMediaByHashResponse_L1_L2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FindRemoteMediaByHashResponse_L1_L2) GetL3() *FindRemoteMediaByHashResponse_L1_L2_L3 {
	if x != nil {
		return x.xxx_hidden_L3
	}
	return nil
}

func (x *FindRemoteMediaByHashResponse_L1_L2) SetL3(v *FindRemoteMediaByHashResponse_L1_L2_L3) {
	x.xxx_hidden_L3 = v
}

func (x *FindRemoteMediaByHashResponse_L1_L2) HasL3() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_L3 != nil
}

func (x *FindRemoteMediaByHashResponse_L1_L2) ClearL3() {
	x.xxx_hidden_L3 = nil
}

type FindRemoteMediaByHashResponse_L1_L2_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	L3 *FindRemoteMediaByHashResponse_L1_L2_L3
}

func (b0 FindRemoteMediaByHashResponse_L1_L2_builder) Build() *FindRemoteMediaByHashResponse_L1_L2 {
	m0 := &FindRemoteMediaByHashResponse_L1_L2{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_L3 = b.L3
	return m0
}

type FindRemoteMediaByHashResponse_L1_L2_L3 struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MediaKey string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindRemoteMediaByHashResponse_L1_L2_L3) Reset() {
	*x = FindRemoteMediaByHashResponse_L1_L2_L3{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRemoteMediaByHashResponse_L1_L2_L3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRemoteMediaByHashResponse_L1_L2_L3) ProtoMessage() {}

func (x *FindRemoteMediaByHashResponse_L1_L2_L3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FindRemoteMediaByHashResponse_L1_L2_L3) GetMediaKey() string {
	if x != nil {
		return x.xxx_hidden_MediaKey
	}
	return ""
}

func (x *FindRemoteMediaByHashResponse_L1_L2_L3) SetMediaKey(v string) {
	x.xxx_hidden_MediaKey = v
}

type FindRemoteMediaByHashResponse_L1_L2_L3_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MediaKey string
}

func (b0 FindRemoteMediaByHashResponse_L1_L2_L3_builder) Build() *FindRemoteMediaByHashResponse_L1_L2_L3 {
	m0 := &FindRemoteMediaByHashResponse_L1_L2_L3{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MediaKey = b.MediaKey
	return m0
}

type CommitUploadRequest_Inner struct {
	state               protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_Receipt  *UploadReceipt                       `protobuf:"bytes,1,opt,name=receipt,proto3"`
	xxx_hidden_Filename string                               `protobuf:"bytes,2,opt,name=filename,proto3"`
	xxx_hidden_Sha1     []byte                               `protobuf:"bytes,3,opt,name=sha1,proto3"`
	xxx_hidden_Ts       *CommitUploadRequest_Inner_Timestamp `protobuf:"bytes,4,opt,name=ts,proto3"`
	xxx_hidden_Quality  int32                                `protobuf:"varint,7,opt,name=quality,proto3"`
	xxx_hidden_Marker   int32                                `protobuf:"varint,10,opt,name=marker,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CommitUploadRequest_Inner) Reset() {
	*x = CommitUploadRequest_Inner{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadRequest_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadRequest_Inner) ProtoMessage() {}

func (x *CommitUploadRequest_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommitUploadRequest_Inner) GetReceipt() *UploadReceipt {
	if x != nil {
		return x.xxx_hidden_Receipt
	}
	return nil
}

func (x *CommitUploadRequest_Inner) GetFilename() string {
	if x != nil {
		return x.xxx_hidden_Filename
	}
	return ""
}

func (x *CommitUploadRequest_Inner) GetSha1() []byte {
	if x != nil {
		return x.xxx_hidden_Sha1
	}
	return nil
}

func (x *CommitUploadRequest_Inner) GetTs() *CommitUploadRequest_Inner_Timestamp {
	if x != nil {
		return x.xxx_hidden_Ts
	}
	return nil
}

func (x *CommitUploadRequest_Inner) GetQuality() int32 {
	if x != nil {
		return x.xxx_hidden_Quality
	}
	return 0
}

func (x *CommitUploadRequest_Inner) GetMarker() int32 {
	if x != nil {
		return x.xxx_hidden_Marker
	}
	return 0
}

func (x *CommitUploadRequest_Inner) SetReceipt(v *UploadReceipt) {
	x.xxx_hidden_Receipt = v
}

func (x *CommitUploadRequest_Inner) SetFilename(v string) {
	x.xxx_hidden_Filename = v
}

func (x *CommitUploadRequest_Inner) SetSha1(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Sha1 = v
}

func (x *CommitUploadRequest_Inner) SetTs(v *CommitUploadRequest_Inner_Timestamp) {
	x.xxx_hidden_Ts = v
}

func (x *CommitUploadRequest_Inner) SetQuality(v int32) {
	x.xxx_hidden_Quality = v
}

func (x *CommitUploadRequest_Inner) SetMarker(v int32) {
	x.xxx_hidden_Marker = v
}

func (x *CommitUploadRequest_Inner) HasReceipt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Receipt != nil
}

func (x *CommitUploadRequest_Inner) HasTs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ts != nil
}

func (x *CommitUploadRequest_Inner) ClearReceipt() {
	x.xxx_hidden_Receipt = nil
}

func (x *CommitUploadRequest_Inner) ClearTs() {
	x.xxx_hidden_Ts = nil
}

type CommitUploadRequest_Inner_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Receipt  *UploadReceipt
	Filename string
	Sha1     []byte
	Ts       *CommitUploadRequest_Inner_Timestamp
	Quality  int32
	Marker   int32
}

func (b0 CommitUploadRequest_Inner_builder) Build() *CommitUploadRequest_Inner {
	m0 := &CommitUploadRequest_Inner{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Receipt = b.Receipt
	x.xxx_hidden_Filename = b.Filename
	x.xxx_hidden_Sha1 = b.Sha1
	x.xxx_hidden_Ts = b.Ts
	x.xxx_hidden_Quality = b.Quality
	x.xxx_hidden_Marker = b.Marker
	return m0
}

type CommitUploadRequest_Device struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Model    string                 `protobuf:"bytes,3,opt,name=model,proto3"`
	xxx_hidden_Make     string                 `protobuf:"bytes,4,opt,name=make,proto3"`
	xxx_hidden_ApiLevel int32                  `protobuf:"varint,5,opt,name=api_level,json=apiLevel,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CommitUploadRequest_Device) Reset() {
	*x = CommitUploadRequest_Device{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadRequest_Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadRequest_Device) ProtoMessage() {}

func (x *CommitUploadRequest_Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommitUploadRequest_Device) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *CommitUploadRequest_Device) GetMake() string {
	if x != nil {
		return x.xxx_hidden_Make
	}
	return ""
}

func (x *CommitUploadRequest_Device) GetApiLevel() int32 {
	if x != nil {
		return x.xxx_hidden_ApiLevel
	}
	return 0
}

func (x *CommitUploadRequest_Device) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *CommitUploadRequest_Device) SetMake(v string) {
	x.xxx_hidden_Make = v
}

func (x *CommitUploadRequest_Device) SetApiLevel(v int32) {
	x.xxx_hidden_ApiLevel = v
}

type CommitUploadRequest_Device_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Model    string
	Make     string
	ApiLevel int32
}

func (b0 CommitUploadRequest_Device_builder) Build() *CommitUploadRequest_Device {
	m0 := &CommitUploadRequest_Device{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Make = b.Make
	x.xxx_hidden_ApiLevel = b.ApiLevel
	return m0
}

type CommitUploadRequest_Inner_Timestamp struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_T     int64                  `protobuf:"varint,1,opt,name=t,proto3"`
	xxx_hidden_Magic int32                  `protobuf:"varint,2,opt,name=magic,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommitUploadRequest_Inner_Timestamp) Reset() {
	*x = CommitUploadRequest_Inner_Timestamp{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadRequest_Inner_Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadRequest_Inner_Timestamp) ProtoMessage() {}

func (x *CommitUploadRequest_Inner_Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommitUploadRequest_Inner_Timestamp) GetT() int64 {
	if x != nil {
		return x.xxx_hidden_T
	}
	return 0
}

func (x *CommitUploadRequest_Inner_Timestamp) GetMagic() int32 {
	if x != nil {
		return x.xxx_hidden_Magic
	}
	return 0
}

func (x *CommitUploadRequest_Inner_Timestamp) SetT(v int64) {
	x.xxx_hidden_T = v
}

func (x *CommitUploadRequest_Inner_Timestamp) SetMagic(v int32) {
	x.xxx_hidden_Magic = v
}

type CommitUploadRequest_Inner_Timestamp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	T     int64
	Magic int32
}

func (b0 CommitUploadRequest_Inner_Timestamp_builder) Build() *CommitUploadRequest_Inner_Timestamp {
	m0 := &CommitUploadRequest_Inner_Timestamp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_T = b.T
	x.xxx_hidden_Magic = b.Magic
	return m0
}

type CommitUploadResponse_L1 struct {
	state         protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_L3 *CommitUploadResponse_L1_L3 `protobuf:"bytes,3,opt,name=l3,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadResponse_L1) Reset() {
	*x = CommitUploadResponse_L1{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadResponse_L1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadResponse_L1) ProtoMessage() {}

func (x *CommitUploadResponse_L1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommitUploadResponse_L1) GetL3() *CommitUploadResponse_L1_L3 {
	if x != nil {
		return x.xxx_hidden_L3
	}
	return nil
}

func (x *CommitUploadResponse_L1) SetL3(v *CommitUploadResponse_L1_L3) {
	x.xxx_hidden_L3 = v
}

func (x *CommitUploadResponse_L1) HasL3() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_L3 != nil
}

func (x *CommitUploadResponse_L1) ClearL3() {
	x.xxx_hidden_L3 = nil
}

type CommitUploadResponse_L1_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	L3 *CommitUploadResponse_L1_L3
}

func (b0 CommitUploadResponse_L1_builder) Build() *CommitUploadResponse_L1 {
	m0 := &CommitUploadResponse_L1{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_L3 = b.L3
	return m0
}

type CommitUploadResponse_L1_L3 struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MediaKey string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CommitUploadResponse_L1_L3) Reset() {
	*x = CommitUploadResponse_L1_L3{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadResponse_L1_L3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadResponse_L1_L3) ProtoMessage() {}

func (x *CommitUploadResponse_L1_L3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommitUploadResponse_L1_L3) GetMediaKey() string {
	if x != nil {
		return x.xxx_hidden_MediaKey
	}
	return ""
}

func (x *CommitUploadResponse_L1_L3) SetMediaKey(v string) {
	x.xxx_hidden_MediaKey = v
}

type CommitUploadResponse_L1_L3_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MediaKey string
}

func (b0 CommitUploadResponse_L1_L3_builder) Build() *CommitUploadResponse_L1_L3 {
	m0 := &CommitUploadResponse_L1_L3{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MediaKey = b.MediaKey
	return m0
}

type PrepareDownloadRequest_KeyInner struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MediaKey string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PrepareDownloadRequest_KeyInner) Reset() {
	*x = PrepareDownloadRequest_KeyInner{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadRequest_KeyInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadRequest_KeyInner) ProtoMessage() {}

func (x *PrepareDownloadRequest_KeyInner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadRequest_KeyInner) GetMediaKey() string {
	if x != nil {
		return x.xxx_hidden_MediaKey
	}
	return ""
}

func (x *PrepareDownloadRequest_KeyInner) SetMediaKey(v string) {
	x.xxx_hidden_MediaKey = v
}

type PrepareDownloadRequest_KeyInner_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MediaKey string
}

func (b0 PrepareDownloadRequest_KeyInner_builder) Build() *PrepareDownloadRequest_KeyInner {
	m0 := &PrepareDownloadRequest_KeyInner{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MediaKey = b.MediaKey
	return m0
}

type PrepareDownloadRequest_KeyOuter struct {
	state            protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Inner *PrepareDownloadRequest_KeyInner `protobuf:"bytes,1,opt,name=inner,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrepareDownloadRequest_KeyOuter) Reset() {
	*x = PrepareDownloadRequest_KeyOuter{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadRequest_KeyOuter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadRequest_KeyOuter) ProtoMessage() {}

func (x *PrepareDownloadRequest_KeyOuter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadRequest_KeyOuter) GetInner() *PrepareDownloadRequest_KeyInner {
	if x != nil {
		return x.xxx_hidden_Inner
	}
	return nil
}

func (x *PrepareDownloadRequest_KeyOuter) SetInner(v *PrepareDownloadRequest_KeyInner) {
	x.xxx_hidden_Inner = v
}

func (x *PrepareDownloadRequest_KeyOuter) HasInner() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Inner != nil
}

func (x *PrepareDownloadRequest_KeyOuter) ClearInner() {
	x.xxx_hidden_Inner = nil
}

type PrepareDownloadRequest_KeyOuter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Inner *PrepareDownloadRequest_KeyInner
}

func (b0 PrepareDownloadRequest_KeyOuter_builder) Build() *PrepareDownloadRequest_KeyOuter {
	m0 := &PrepareDownloadRequest_KeyOuter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Inner = b.Inner
	return m0
}

type PrepareDownloadRequest_Empty struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDownloadRequest_Empty) Reset() {
	*x = PrepareDownloadRequest_Empty{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadRequest_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadRequest_Empty) ProtoMessage() {}

func (x *PrepareDownloadRequest_Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PrepareDownloadRequest_Empty_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PrepareDownloadRequest_Empty_builder) Build() *PrepareDownloadRequest_Empty {
	m0 := &PrepareDownloadRequest_Empty{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PrepareDownloadRequest_OpaqueF1Inner struct {
	state         protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_F2 *PrepareDownloadRequest_Empty `protobuf:"bytes,2,opt,name=f2,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDownloadRequest_OpaqueF1Inner) Reset() {
	*x = PrepareDownloadRequest_OpaqueF1Inner{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadRequest_OpaqueF1Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadRequest_OpaqueF1Inner) ProtoMessage() {}

func (x *PrepareDownloadRequest_OpaqueF1Inner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadRequest_OpaqueF1Inner) GetF2() *PrepareDownloadRequest_Empty {
	if x != nil {
		return x.xxx_hidden_F2
	}
	return nil
}

func (x *PrepareDownloadRequest_OpaqueF1Inner) SetF2(v *PrepareDownloadRequest_Empty) {
	x.xxx_hidden_F2 = v
}

func (x *PrepareDownloadRequest_OpaqueF1Inner) HasF2() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_F2 != nil
}

func (x *PrepareDownloadRequest_OpaqueF1Inner) ClearF2() {
	x.xxx_hidden_F2 = nil
}

type PrepareDownloadRequest_OpaqueF1Inner_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	F2 *PrepareDownloadRequest_Empty
}

func (b0 PrepareDownloadRequest_OpaqueF1Inner_builder) Build() *PrepareDownloadRequest_OpaqueF1Inner {
	m0 := &PrepareDownloadRequest_OpaqueF1Inner{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_F2 = b.F2
	return m0
}

type PrepareDownloadRequest_OpaqueF1 struct {
	state         protoimpl.MessageState                `protogen:"opaque.v1"`
	xxx_hidden_F7 *PrepareDownloadRequest_OpaqueF1Inner `protobuf:"bytes,7,opt,name=f7,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDownloadRequest_OpaqueF1) Reset() {
	*x = PrepareDownloadRequest_OpaqueF1{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadRequest_OpaqueF1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadRequest_OpaqueF1) ProtoMessage() {}

func (x *PrepareDownloadRequest_OpaqueF1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadRequest_OpaqueF1) GetF7() *PrepareDownloadRequest_OpaqueF1Inner {
	if x != nil {
		return x.xxx_hidden_F7
	}
	return nil
}

func (x *PrepareDownloadRequest_OpaqueF1) SetF7(v *PrepareDownloadRequest_OpaqueF1Inner) {
	x.xxx_hidden_F7 = v
}

func (x *PrepareDownloadRequest_OpaqueF1) HasF7() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_F7 != nil
}

func (x *PrepareDownloadRequest_OpaqueF1) ClearF7() {
	x.xxx_hidden_F7 = nil
}

type PrepareDownloadRequest_OpaqueF1_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	F7 *PrepareDownloadRequest_OpaqueF1Inner
}

func (b0 PrepareDownloadRequest_OpaqueF1_builder) Build() *PrepareDownloadRequest_OpaqueF1 {
	m0 := &PrepareDownloadRequest_OpaqueF1{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_F7 = b.F7
	return m0
}

type PrepareDownloadRequest_OpaqueF5Inner5 struct {
	state         protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_F1 *PrepareDownloadRequest_Empty `protobuf:"bytes,1,opt,name=f1,proto3"`
	xxx_hidden_F3 int32                         `protobuf:"varint,3,opt,name=f3,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDownloadRequest_OpaqueF5Inner5) Reset() {
	*x = PrepareDownloadRequest_OpaqueF5Inner5{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadRequest_OpaqueF5Inner5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadRequest_OpaqueF5Inner5) ProtoMessage() {}

func (x *PrepareDownloadRequest_OpaqueF5Inner5) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadRequest_OpaqueF5Inner5) GetF1() *PrepareDownloadRequest_Empty {
	if x != nil {
		return x.xxx_hidden_F1
	}
	return nil
}

func (x *PrepareDownloadRequest_OpaqueF5Inner5) GetF3() int32 {
	if x != nil {
		return x.xxx_hidden_F3
	}
	return 0
}

func (x *PrepareDownloadRequest_OpaqueF5Inner5) SetF1(v *PrepareDownloadRequest_Empty) {
	x.xxx_hidden_F1 = v
}

func (x *PrepareDownloadRequest_OpaqueF5Inner5) SetF3(v int32) {
	x.xxx_hidden_F3 = v
}

func (x *PrepareDownloadRequest_OpaqueF5Inner5) HasF1() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_F1 != nil
}

func (x *PrepareDownloadRequest_OpaqueF5Inner5) ClearF1() {
	x.xxx_hidden_F1 = nil
}

type PrepareDownloadRequest_OpaqueF5Inner5_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	F1 *PrepareDownloadRequest_Empty
	F3 int32
}

func (b0 PrepareDownloadRequest_OpaqueF5Inner5_builder) Build() *PrepareDownloadRequest_OpaqueF5Inner5 {
	m0 := &PrepareDownloadRequest_OpaqueF5Inner5{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_F1 = b.F1
	x.xxx_hidden_F3 = b.F3
	return m0
}

type PrepareDownloadRequest_OpaqueF5 struct {
	state         protoimpl.MessageState                 `protogen:"opaque.v1"`
	xxx_hidden_F2 *PrepareDownloadRequest_Empty          `protobuf:"bytes,2,opt,name=f2,proto3"`
	xxx_hidden_F3 *PrepareDownloadRequest_Empty          `protobuf:"bytes,3,opt,name=f3,proto3"`
	xxx_hidden_F5 *PrepareDownloadRequest_OpaqueF5Inner5 `protobuf:"bytes,5,opt,name=f5,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDownloadRequest_OpaqueF5) Reset() {
	*x = PrepareDownloadRequest_OpaqueF5{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadRequest_OpaqueF5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadRequest_OpaqueF5) ProtoMessage() {}

func (x *PrepareDownloadRequest_OpaqueF5) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadRequest_OpaqueF5) GetF2() *PrepareDownloadRequest_Empty {
	if x != nil {
		return x.xxx_hidden_F2
	}
	return nil
}

func (x *PrepareDownloadRequest_OpaqueF5) GetF3() *PrepareDownloadRequest_Empty {
	if x != nil {
		return x.xxx_hidden_F3
	}
	return nil
}

func (x *PrepareDownloadRequest_OpaqueF5) GetF5() *PrepareDownloadRequest_OpaqueF5Inner5 {
	if x != nil {
		return x.xxx_hidden_F5
	}
	return nil
}

func (x *PrepareDownloadRequest_OpaqueF5) SetF2(v *PrepareDownloadRequest_Empty) {
	x.xxx_hidden_F2 = v
}

func (x *PrepareDownloadRequest_OpaqueF5) SetF3(v *PrepareDownloadRequest_Empty) {
	x.xxx_hidden_F3 = v
}

func (x *PrepareDownloadRequest_OpaqueF5) SetF5(v *PrepareDownloadRequest_OpaqueF5Inner5) {
	x.xxx_hidden_F5 = v
}

func (x *PrepareDownloadRequest_OpaqueF5) HasF2() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_F2 != nil
}

func (x *PrepareDownloadRequest_OpaqueF5) HasF3() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_F3 != nil
}

func (x *PrepareDownloadRequest_OpaqueF5) HasF5() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_F5 != nil
}

func (x *PrepareDownloadRequest_OpaqueF5) ClearF2() {
	x.xxx_hidden_F2 = nil
}

func (x *PrepareDownloadRequest_OpaqueF5) ClearF3() {
	x.xxx_hidden_F3 = nil
}

func (x *PrepareDownloadRequest_OpaqueF5) ClearF5() {
	x.xxx_hidden_F5 = nil
}

type PrepareDownloadRequest_OpaqueF5_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	F2 *PrepareDownloadRequest_Empty
	F3 *PrepareDownloadRequest_Empty
	F5 *PrepareDownloadRequest_OpaqueF5Inner5
}

func (b0 PrepareDownloadRequest_OpaqueF5_builder) Build() *PrepareDownloadRequest_OpaqueF5 {
	m0 := &PrepareDownloadRequest_OpaqueF5{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_F2 = b.F2
	x.xxx_hidden_F3 = b.F3
	x.xxx_hidden_F5 = b.F5
	return m0
}

type PrepareDownloadRequest_Opaque struct {
	state         protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_F1 *PrepareDownloadRequest_OpaqueF1 `protobuf:"bytes,1,opt,name=f1,proto3"`
	xxx_hidden_F5 *PrepareDownloadRequest_OpaqueF5 `protobuf:"bytes,5,opt,name=f5,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDownloadRequest_Opaque) Reset() {
	*x = PrepareDownloadRequest_Opaque{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadRequest_Opaque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadRequest_Opaque) ProtoMessage() {}

func (x *PrepareDownloadRequest_Opaque) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadRequest_Opaque) GetF1() *PrepareDownloadRequest_OpaqueF1 {
	if x != nil {
		return x.xxx_hidden_F1
	}
	return nil
}

func (x *PrepareDownloadRequest_Opaque) GetF5() *PrepareDownloadRequest_OpaqueF5 {
	if x != nil {
		return x.xxx_hidden_F5
	}
	return nil
}

func (x *PrepareDownloadRequest_Opaque) SetF1(v *PrepareDownloadRequest_OpaqueF1) {
	x.xxx_hidden_F1 = v
}

func (x *PrepareDownloadRequest_Opaque) SetF5(v *PrepareDownloadRequest_OpaqueF5) {
	x.xxx_hidden_F5 = v
}

func (x *PrepareDownloadRequest_Opaque) HasF1() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_F1 != nil
}

func (x *PrepareDownloadRequest_Opaque) HasF5() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_F5 != nil
}

func (x *PrepareDownloadRequest_Opaque) ClearF1() {
	x.xxx_hidden_F1 = nil
}

func (x *PrepareDownloadRequest_Opaque) ClearF5() {
	x.xxx_hidden_F5 = nil
}

type PrepareDownloadRequest_Opaque_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	F1 *PrepareDownloadRequest_OpaqueF1
	F5 *PrepareDownloadRequest_OpaqueF5
}

func (b0 PrepareDownloadRequest_Opaque_builder) Build() *PrepareDownloadRequest_Opaque {
	m0 := &PrepareDownloadRequest_Opaque{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_F1 = b.F1
	x.xxx_hidden_F5 = b.F5
	return m0
}

type LibStateRequest_Inner struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SyncToken string                 `protobuf:"bytes,6,opt,name=sync_token,json=syncToken,proto3"`
	xxx_hidden_Mode      int32                  `protobuf:"varint,7,opt,name=mode,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LibStateRequest_Inner) Reset() {
	*x = LibStateRequest_Inner{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibStateRequest_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibStateRequest_Inner) ProtoMessage() {}

func (x *LibStateRequest_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LibStateRequest_Inner) GetSyncToken() string {
	if x != nil {
		return x.xxx_hidden_SyncToken
	}
	return ""
}

func (x *LibStateRequest_Inner) GetMode() int32 {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return 0
}

func (x *LibStateRequest_Inner) SetSyncToken(v string) {
	x.xxx_hidden_SyncToken = v
}

func (x *LibStateRequest_Inner) SetMode(v int32) {
	x.xxx_hidden_Mode = v
}

type LibStateRequest_Inner_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SyncToken string
	Mode      int32
}

func (b0 LibStateRequest_Inner_builder) Build() *LibStateRequest_Inner {
	m0 := &LibStateRequest_Inner{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SyncToken = b.SyncToken
	x.xxx_hidden_Mode = b.Mode
	return m0
}

type LibStateResponse_Body struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items     *[]*MediaItem          `protobuf:"bytes,2,rep,name=items,proto3"`
	xxx_hidden_SyncToken string                 `protobuf:"bytes,6,opt,name=sync_token,json=syncToken,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LibStateResponse_Body) Reset() {
	*x = LibStateResponse_Body{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibStateResponse_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibStateResponse_Body) ProtoMessage() {}

func (x *LibStateResponse_Body) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LibStateResponse_Body) GetItems() []*MediaItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *LibStateResponse_Body) GetSyncToken() string {
	if x != nil {
		return x.xxx_hidden_SyncToken
	}
	return ""
}

func (x *LibStateResponse_Body) SetItems(v []*MediaItem) {
	x.xxx_hidden_Items = &v
}

func (x *LibStateResponse_Body) SetSyncToken(v string) {
	x.xxx_hidden_SyncToken = v
}

type LibStateResponse_Body_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items     []*MediaItem
	SyncToken string
}

func (b0 LibStateResponse_Body_builder) Build() *LibStateResponse_Body {
	m0 := &LibStateResponse_Body{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_SyncToken = b.SyncToken
	return m0
}

type MediaItem_Meta struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filename       string                 `protobuf:"bytes,4,opt,name=filename,proto3"`
	xxx_hidden_UtcTimestampMs int64                  `protobuf:"varint,7,opt,name=utc_timestamp_ms,json=utcTimestampMs,proto3"`
	xxx_hidden_SizeBytes      int64                  `protobuf:"varint,10,opt,name=size_bytes,json=sizeBytes,proto3"`
	xxx_hidden_Hashes         *MediaItem_Meta_Hashes `protobuf:"bytes,13,opt,name=hashes,proto3"`
	xxx_hidden_Trash          *MediaItem_Trash       `protobuf:"bytes,16,opt,name=trash,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MediaItem_Meta) Reset() {
	*x = MediaItem_Meta{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem_Meta) ProtoMessage() {}

func (x *MediaItem_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaItem_Meta) GetFilename() string {
	if x != nil {
		return x.xxx_hidden_Filename
	}
	return ""
}

func (x *MediaItem_Meta) GetUtcTimestampMs() int64 {
	if x != nil {
		return x.xxx_hidden_UtcTimestampMs
	}
	return 0
}

func (x *MediaItem_Meta) GetSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_SizeBytes
	}
	return 0
}

func (x *MediaItem_Meta) GetHashes() *MediaItem_Meta_Hashes {
	if x != nil {
		return x.xxx_hidden_Hashes
	}
	return nil
}

func (x *MediaItem_Meta) GetTrash() *MediaItem_Trash {
	if x != nil {
		return x.xxx_hidden_Trash
	}
	return nil
}

func (x *MediaItem_Meta) SetFilename(v string) {
	x.xxx_hidden_Filename = v
}

func (x *MediaItem_Meta) SetUtcTimestampMs(v int64) {
	x.xxx_hidden_UtcTimestampMs = v
}

func (x *MediaItem_Meta) SetSizeBytes(v int64) {
	x.xxx_hidden_SizeBytes = v
}

func (x *MediaItem_Meta) SetHashes(v *MediaItem_Meta_Hashes) {
	x.xxx_hidden_Hashes = v
}

func (x *MediaItem_Meta) SetTrash(v *MediaItem_Trash) {
	x.xxx_hidden_Trash = v
}

func (x *MediaItem_Meta) HasHashes() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Hashes != nil
}

func (x *MediaItem_Meta) HasTrash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Trash != nil
}

func (x *MediaItem_Meta) ClearHashes() {
	x.xxx_hidden_Hashes = nil
}

func (x *MediaItem_Meta) ClearTrash() {
	x.xxx_hidden_Trash = nil
}

type MediaItem_Meta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filename       string
	UtcTimestampMs int64
	SizeBytes      int64
	Hashes         *MediaItem_Meta_Hashes
	Trash          *MediaItem_Trash
}

func (b0 MediaItem_Meta_builder) Build() *MediaItem_Meta {
	m0 := &MediaItem_Meta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filename = b.Filename
	x.xxx_hidden_UtcTimestampMs = b.UtcTimestampMs
	x.xxx_hidden_SizeBytes = b.SizeBytes
	x.xxx_hidden_Hashes = b.Hashes
	x.xxx_hidden_Trash = b.Trash
	return m0
}

type MediaItem_Trash struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TrashedAt int64                  `protobuf:"varint,3,opt,name=trashed_at,json=trashedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaItem_Trash) Reset() {
	*x = MediaItem_Trash{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem_Trash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem_Trash) ProtoMessage() {}

func (x *MediaItem_Trash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaItem_Trash) GetTrashedAt() int64 {
	if x != nil {
		return x.xxx_hidden_TrashedAt
	}
	return 0
}

func (x *MediaItem_Trash) SetTrashedAt(v int64) {
	x.xxx_hidden_TrashedAt = v
}

type MediaItem_Trash_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TrashedAt int64
}

func (b0 MediaItem_Trash_builder) Build() *MediaItem_Trash {
	m0 := &MediaItem_Trash{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TrashedAt = b.TrashedAt
	return m0
}

type MediaItem_Kind struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type  int32                  `protobuf:"varint,1,opt,name=type,proto3"`
	xxx_hidden_Photo *MediaItem_Photo       `protobuf:"bytes,2,opt,name=photo,proto3"`
	xxx_hidden_Video *MediaItem_Video       `protobuf:"bytes,3,opt,name=video,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MediaItem_Kind) Reset() {
	*x = MediaItem_Kind{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem_Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem_Kind) ProtoMessage() {}

func (x *MediaItem_Kind) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaItem_Kind) GetType() int32 {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return 0
}

func (x *MediaItem_Kind) GetPhoto() *MediaItem_Photo {
	if x != nil {
		return x.xxx_hidden_Photo
	}
	return nil
}

func (x *MediaItem_Kind) GetVideo() *MediaItem_Video {
	if x != nil {
		return x.xxx_hidden_Video
	}
	return nil
}

func (x *MediaItem_Kind) SetType(v int32) {
	x.xxx_hidden_Type = v
}

func (x *MediaItem_Kind) SetPhoto(v *MediaItem_Photo) {
	x.xxx_hidden_Photo = v
}

func (x *MediaItem_Kind) SetVideo(v *MediaItem_Video) {
	x.xxx_hidden_Video = v
}

func (x *MediaItem_Kind) HasPhoto() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Photo != nil
}

func (x *MediaItem_Kind) HasVideo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Video != nil
}

func (x *MediaItem_Kind) ClearPhoto() {
	x.xxx_hidden_Photo = nil
}

func (x *MediaItem_Kind) ClearVideo() {
	x.xxx_hidden_Video = nil
}

type MediaItem_Kind_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type  int32
	Photo *MediaItem_Photo
	Video *MediaItem_Video
}

func (b0 MediaItem_Kind_builder) Build() *MediaItem_Kind {
	m0 := &MediaItem_Kind{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Photo = b.Photo
	x.xxx_hidden_Video = b.Video
	return m0
}

type MediaItem_Photo struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItem_Photo) Reset() {
	*x = MediaItem_Photo{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem_Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem_Photo) ProtoMessage() {}

func (x *MediaItem_Photo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type MediaItem_Photo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 MediaItem_Photo_builder) Build() *MediaItem_Photo {
	m0 := &MediaItem_Photo{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type MediaItem_Video struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItem_Video) Reset() {
	*x = MediaItem_Video{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem_Video) ProtoMessage() {}

func (x *MediaItem_Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type MediaItem_Video_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 MediaItem_Video_builder) Build() *MediaItem_Video {
	m0 := &MediaItem_Video{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type MediaItem_Meta_Hashes struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sha1 []byte                 `protobuf:"bytes,1,opt,name=sha1,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaItem_Meta_Hashes) Reset() {
	*x = MediaItem_Meta_Hashes{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem_Meta_Hashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem_Meta_Hashes) ProtoMessage() {}

func (x *MediaItem_Meta_Hashes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaItem_Meta_Hashes) GetSha1() []byte {
	if x != nil {
		return x.xxx_hidden_Sha1
	}
	return nil
}

func (x *MediaItem_Meta_Hashes) SetSha1(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Sha1 = v
}

type MediaItem_Meta_Hashes_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sha1 []byte
}

func (b0 MediaItem_Meta_Hashes_builder) Build() *MediaItem_Meta_Hashes {
	m0 := &MediaItem_Meta_Hashes{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sha1 = b.Sha1
	return m0
}

type PrepareDownloadResponse_L1 struct {
	state         protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_L5 *PrepareDownloadResponse_L1_L5 `protobuf:"bytes,5,opt,name=l5,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDownloadResponse_L1) Reset() {
	*x = PrepareDownloadResponse_L1{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadResponse_L1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadResponse_L1) ProtoMessage() {}

func (x *PrepareDownloadResponse_L1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadResponse_L1) GetL5() *PrepareDownloadResponse_L1_L5 {
	if x != nil {
		return x.xxx_hidden_L5
	}
	return nil
}

func (x *PrepareDownloadResponse_L1) SetL5(v *PrepareDownloadResponse_L1_L5) {
	x.xxx_hidden_L5 = v
}

func (x *PrepareDownloadResponse_L1) HasL5() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_L5 != nil
}

func (x *PrepareDownloadResponse_L1) ClearL5() {
	x.xxx_hidden_L5 = nil
}

type PrepareDownloadResponse_L1_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	L5 *PrepareDownloadResponse_L1_L5
}

func (b0 PrepareDownloadResponse_L1_builder) Build() *PrepareDownloadResponse_L1 {
	m0 := &PrepareDownloadResponse_L1{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_L5 = b.L5
	return m0
}

type PrepareDownloadResponse_L1_L5 struct {
	state                protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_MediaType int32                                `protobuf:"varint,1,opt,name=media_type,json=mediaType,proto3"`
	xxx_hidden_Image     *PrepareDownloadResponse_L1_L5_Image `protobuf:"bytes,2,opt,name=image,proto3"`
	xxx_hidden_Video     *PrepareDownloadResponse_L1_L5_Video `protobuf:"bytes,3,opt,name=video,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PrepareDownloadResponse_L1_L5) Reset() {
	*x = PrepareDownloadResponse_L1_L5{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadResponse_L1_L5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadResponse_L1_L5) ProtoMessage() {}

func (x *PrepareDownloadResponse_L1_L5) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadResponse_L1_L5) GetMediaType() int32 {
	if x != nil {
		return x.xxx_hidden_MediaType
	}
	return 0
}

func (x *PrepareDownloadResponse_L1_L5) GetImage() *PrepareDownloadResponse_L1_L5_Image {
	if x != nil {
		return x.xxx_hidden_Image
	}
	return nil
}

func (x *PrepareDownloadResponse_L1_L5) GetVideo() *PrepareDownloadResponse_L1_L5_Video {
	if x != nil {
		return x.xxx_hidden_Video
	}
	return nil
}

func (x *PrepareDownloadResponse_L1_L5) SetMediaType(v int32) {
	x.xxx_hidden_MediaType = v
}

func (x *PrepareDownloadResponse_L1_L5) SetImage(v *PrepareDownloadResponse_L1_L5_Image) {
	x.xxx_hidden_Image = v
}

func (x *PrepareDownloadResponse_L1_L5) SetVideo(v *PrepareDownloadResponse_L1_L5_Video) {
	x.xxx_hidden_Video = v
}

func (x *PrepareDownloadResponse_L1_L5) HasImage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Image != nil
}

func (x *PrepareDownloadResponse_L1_L5) HasVideo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Video != nil
}

func (x *PrepareDownloadResponse_L1_L5) ClearImage() {
	x.xxx_hidden_Image = nil
}

func (x *PrepareDownloadResponse_L1_L5) ClearVideo() {
	x.xxx_hidden_Video = nil
}

type PrepareDownloadResponse_L1_L5_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MediaType int32
	Image     *PrepareDownloadResponse_L1_L5_Image
	Video     *PrepareDownloadResponse_L1_L5_Video
}

func (b0 PrepareDownloadResponse_L1_L5_builder) Build() *PrepareDownloadResponse_L1_L5 {
	m0 := &PrepareDownloadResponse_L1_L5{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MediaType = b.MediaType
	x.xxx_hidden_Image = b.Image
	x.xxx_hidden_Video = b.Video
	return m0
}

type PrepareDownloadResponse_L1_L5_Image struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EditedUrl   string                 `protobuf:"bytes,5,opt,name=edited_url,json=editedUrl,proto3"`
	xxx_hidden_OriginalUrl string                 `protobuf:"bytes,6,opt,name=original_url,json=originalUrl,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PrepareDownloadResponse_L1_L5_Image) Reset() {
	*x = PrepareDownloadResponse_L1_L5_Image{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadResponse_L1_L5_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadResponse_L1_L5_Image) ProtoMessage() {}

func (x *PrepareDownloadResponse_L1_L5_Image) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadResponse_L1_L5_Image) GetEditedUrl() string {
	if x != nil {
		return x.xxx_hidden_EditedUrl
	}
	return ""
}

func (x *PrepareDownloadResponse_L1_L5_Image) GetOriginalUrl() string {
	if x != nil {
		return x.xxx_hidden_OriginalUrl
	}
	return ""
}

func (x *PrepareDownloadResponse_L1_L5_Image) SetEditedUrl(v string) {
	x.xxx_hidden_EditedUrl = v
}

func (x *PrepareDownloadResponse_L1_L5_Image) SetOriginalUrl(v string) {
	x.xxx_hidden_OriginalUrl = v
}

type PrepareDownloadResponse_L1_L5_Image_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EditedUrl   string
	OriginalUrl string
}

func (b0 PrepareDownloadResponse_L1_L5_Image_builder) Build() *PrepareDownloadResponse_L1_L5_Image {
	m0 := &PrepareDownloadResponse_L1_L5_Image{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EditedUrl = b.EditedUrl
	x.xxx_hidden_OriginalUrl = b.OriginalUrl
	return m0
}

type PrepareDownloadResponse_L1_L5_Video struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContentVersion string                 `protobuf:"bytes,1,opt,name=content_version,json=contentVersion,proto3"`
	xxx_hidden_Kind           int32                  `protobuf:"varint,3,opt,name=kind,proto3"`
	xxx_hidden_DownloadUrl    string                 `protobuf:"bytes,5,opt,name=download_url,json=downloadUrl,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PrepareDownloadResponse_L1_L5_Video) Reset() {
	*x = PrepareDownloadResponse_L1_L5_Video{}
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDownloadResponse_L1_L5_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDownloadResponse_L1_L5_Video) ProtoMessage() {}

func (x *PrepareDownloadResponse_L1_L5_Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpmc_v1_messages_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareDownloadResponse_L1_L5_Video) GetContentVersion() string {
	if x != nil {
		return x.xxx_hidden_ContentVersion
	}
	return ""
}

func (x *PrepareDownloadResponse_L1_L5_Video) GetKind() int32 {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return 0
}

func (x *PrepareDownloadResponse_L1_L5_Video) GetDownloadUrl() string {
	if x != nil {
		return x.xxx_hidden_DownloadUrl
	}
	return ""
}

func (x *PrepareDownloadResponse_L1_L5_Video) SetContentVersion(v string) {
	x.xxx_hidden_ContentVersion = v
}

func (x *PrepareDownloadResponse_L1_L5_Video) SetKind(v int32) {
	x.xxx_hidden_Kind = v
}

func (x *PrepareDownloadResponse_L1_L5_Video) SetDownloadUrl(v string) {
	x.xxx_hidden_DownloadUrl = v
}

type PrepareDownloadResponse_L1_L5_Video_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContentVersion string
	Kind           int32
	DownloadUrl    string
}

func (b0 PrepareDownloadResponse_L1_L5_Video_builder) Build() *PrepareDownloadResponse_L1_L5_Video {
	m0 := &PrepareDownloadResponse_L1_L5_Video{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ContentVersion = b.ContentVersion
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_DownloadUrl = b.DownloadUrl
	return m0
}

var File_proto_gpmc_v1_messages_proto protoreflect.FileDescriptor

const file_proto_gpmc_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/gpmc/v1/messages.proto\x12\agpmc.v1\"t\n" +
	"\x15GetUploadTokenRequest\x12\x0e\n" +
	"\x02f1\x18\x01 \x01(\x05R\x02f1\x12\x0e\n" +
	"\x02f2\x18\x02 \x01(\x05R\x02f2\x12\x0e\n" +
	"\x02f3\x18\x03 \x01(\x05R\x02f3\x12\x0e\n" +
	"\x02f4\x18\x04 \x01(\x05R\x02f4\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\"\xa1\x02\n" +
	"\x1cFindRemoteMediaByHashRequest\x12A\n" +
	"\x05inner\x18\x01 \x01(\v2+.gpmc.v1.FindRemoteMediaByHashRequest.InnerR\x05inner\x1a\xbd\x01\n" +
	"\x05Inner\x12D\n" +
	"\x04hash\x18\x01 \x01(\v20.gpmc.v1.FindRemoteMediaByHashRequest.Inner.HashR\x04hash\x12I\n" +
	"\x06marker\x18\x02 \x01(\v21.gpmc.v1.FindRemoteMediaByHashRequest.Inner.EmptyR\x06marker\x1a\x1a\n" +
	"\x04Hash\x12\x12\n" +
	"\x04sha1\x18\x01 \x01(\fR\x04sha1\x1a\a\n" +
	"\x05Empty\"\x89\x02\n" +
	"\x1dFindRemoteMediaByHashResponse\x129\n" +
	"\x02l1\x18\x01 \x01(\v2).gpmc.v1.FindRemoteMediaByHashResponse.L1R\x02l1\x1a\xac\x01\n" +
	"\x02L1\x12<\n" +
	"\x02l2\x18\x02 \x01(\v2,.gpmc.v1.FindRemoteMediaByHashResponse.L1.L2R\x02l2\x1ah\n" +
	"\x02L2\x12?\n" +
	"\x02l3\x18\x02 \x01(\v2/.gpmc.v1.FindRemoteMediaByHashResponse.L1.L2.L3R\x02l3\x1a!\n" +
	"\x02L3\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\"?\n" +
	"\rUploadReceipt\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x12\x16\n" +
	"\x06field2\x18\x02 \x01(\fR\x06field2\"\x84\x04\n" +
	"\x13CommitUploadRequest\x128\n" +
	"\x05inner\x18\x01 \x01(\v2\".gpmc.v1.CommitUploadRequest.InnerR\x05inner\x12;\n" +
	"\x06device\x18\x02 \x01(\v2#.gpmc.v1.CommitUploadRequest.DeviceR\x06device\x12\x18\n" +
	"\atrailer\x18\x03 \x01(\fR\atrailer\x1a\x8a\x02\n" +
	"\x05Inner\x120\n" +
	"\areceipt\x18\x01 \x01(\v2\x16.gpmc.v1.UploadReceiptR\areceipt\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04sha1\x18\x03 \x01(\fR\x04sha1\x12<\n" +
	"\x02ts\x18\x04 \x01(\v2,.gpmc.v1.CommitUploadRequest.Inner.TimestampR\x02ts\x12\x18\n" +
	"\aquality\x18\a \x01(\x05R\aquality\x12\x16\n" +
	"\x06marker\x18\n" +
	" \x01(\x05R\x06marker\x1a/\n" +
	"\tTimestamp\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\x14\n" +
	"\x05magic\x18\x02 \x01(\x05R\x05magic\x1aO\n" +
	"\x06Device\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04make\x18\x04 \x01(\tR\x04make\x12\x1b\n" +
	"\tapi_level\x18\x05 \x01(\x05R\bapiLevel\"\xa6\x01\n" +
	"\x14CommitUploadResponse\x120\n" +
	"\x02l1\x18\x01 \x01(\v2 .gpmc.v1.CommitUploadResponse.L1R\x02l1\x1a\\\n" +
	"\x02L1\x123\n" +
	"\x02l3\x18\x03 \x01(\v2#.gpmc.v1.CommitUploadResponse.L1.L3R\x02l3\x1a!\n" +
	"\x02L3\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\"\xb7\x06\n" +
	"\x16PrepareDownloadRequest\x12:\n" +
	"\x03key\x18\x01 \x01(\v2(.gpmc.v1.PrepareDownloadRequest.KeyOuterR\x03key\x12>\n" +
	"\x06opaque\x18\x02 \x01(\v2&.gpmc.v1.PrepareDownloadRequest.OpaqueR\x06opaque\x1a'\n" +
	"\bKeyInner\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x1aJ\n" +
	"\bKeyOuter\x12>\n" +
	"\x05inner\x18\x01 \x01(\v2(.gpmc.v1.PrepareDownloadRequest.KeyInnerR\x05inner\x1a\a\n" +
	"\x05Empty\x1aF\n" +
	"\rOpaqueF1Inner\x125\n" +
	"\x02f2\x18\x02 \x01(\v2%.gpmc.v1.PrepareDownloadRequest.EmptyR\x02f2\x1aI\n" +
	"\bOpaqueF1\x12=\n" +
	"\x02f7\x18\a \x01(\v2-.gpmc.v1.PrepareDownloadRequest.OpaqueF1InnerR\x02f7\x1aW\n" +
	"\x0eOpaqueF5Inner5\x125\n" +
	"\x02f1\x18\x01 \x01(\v2%.gpmc.v1.PrepareDownloadRequest.EmptyR\x02f1\x12\x0e\n" +
	"\x02f3\x18\x03 \x01(\x05R\x02f3\x1a\xb8\x01\n" +
	"\bOpaqueF5\x125\n" +
	"\x02f2\x18\x02 \x01(\v2%.gpmc.v1.PrepareDownloadRequest.EmptyR\x02f2\x125\n" +
	"\x02f3\x18\x03 \x01(\v2%.gpmc.v1.PrepareDownloadRequest.EmptyR\x02f3\x12>\n" +
	"\x02f5\x18\x05 \x01(\v2..gpmc.v1.PrepareDownloadRequest.OpaqueF5Inner5R\x02f5\x1a|\n" +
	"\x06Opaque\x128\n" +
	"\x02f1\x18\x01 \x01(\v2(.gpmc.v1.PrepareDownloadRequest.OpaqueF1R\x02f1\x128\n" +
	"\x02f5\x18\x05 \x01(\v2(.gpmc.v1.PrepareDownloadRequest.OpaqueF5R\x02f5\"\x83\x01\n" +
	"\x0fLibStateRequest\x124\n" +
	"\x05inner\x18\x01 \x01(\v2\x1e.gpmc.v1.LibStateRequest.InnerR\x05inner\x1a:\n" +
	"\x05Inner\x12\x1d\n" +
	"\n" +
	"sync_token\x18\x06 \x01(\tR\tsyncToken\x12\x12\n" +
	"\x04mode\x18\a \x01(\x05R\x04mode\"\x97\x01\n" +
	"\x10LibStateResponse\x122\n" +
	"\x04body\x18\x01 \x01(\v2\x1e.gpmc.v1.LibStateResponse.BodyR\x04body\x1aO\n" +
	"\x04Body\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.gpmc.v1.MediaItemR\x05items\x12\x1d\n" +
	"\n" +
	"sync_token\x18\x06 \x01(\tR\tsyncToken\"\xac\x04\n" +
	"\tMediaItem\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x12+\n" +
	"\x04meta\x18\x02 \x01(\v2\x17.gpmc.v1.MediaItem.MetaR\x04meta\x12+\n" +
	"\x04kind\x18\x05 \x01(\v2\x17.gpmc.v1.MediaItem.KindR\x04kind\x1a\xf1\x01\n" +
	"\x04Meta\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12(\n" +
	"\x10utc_timestamp_ms\x18\a \x01(\x03R\x0eutcTimestampMs\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\n" +
	" \x01(\x03R\tsizeBytes\x126\n" +
	"\x06hashes\x18\r \x01(\v2\x1e.gpmc.v1.MediaItem.Meta.HashesR\x06hashes\x12.\n" +
	"\x05trash\x18\x10 \x01(\v2\x18.gpmc.v1.MediaItem.TrashR\x05trash\x1a\x1c\n" +
	"\x06Hashes\x12\x12\n" +
	"\x04sha1\x18\x01 \x01(\fR\x04sha1\x1a&\n" +
	"\x05Trash\x12\x1d\n" +
	"\n" +
	"trashed_at\x18\x03 \x01(\x03R\ttrashedAt\x1az\n" +
	"\x04Kind\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12.\n" +
	"\x05photo\x18\x02 \x01(\v2\x18.gpmc.v1.MediaItem.PhotoR\x05photo\x12.\n" +
	"\x05video\x18\x03 \x01(\v2\x18.gpmc.v1.MediaItem.VideoR\x05video\x1a\a\n" +
	"\x05Photo\x1a\a\n" +
	"\x05Video\"\xef\x03\n" +
	"\x17PrepareDownloadResponse\x123\n" +
	"\x02l1\x18\x01 \x01(\v2#.gpmc.v1.PrepareDownloadResponse.L1R\x02l1\x1a\x9e\x03\n" +
	"\x02L1\x126\n" +
	"\x02l5\x18\x05 \x01(\v2&.gpmc.v1.PrepareDownloadResponse.L1.L5R\x02l5\x1a\xdf\x02\n" +
	"\x02L5\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\x05R\tmediaType\x12B\n" +
	"\x05image\x18\x02 \x01(\v2,.gpmc.v1.PrepareDownloadResponse.L1.L5.ImageR\x05image\x12B\n" +
	"\x05video\x18\x03 \x01(\v2,.gpmc.v1.PrepareDownloadResponse.L1.L5.VideoR\x05video\x1aI\n" +
	"\x05Image\x12\x1d\n" +
	"\n" +
	"edited_url\x18\x05 \x01(\tR\teditedUrl\x12!\n" +
	"\foriginal_url\x18\x06 \x01(\tR\voriginalUrl\x1ag\n" +
	"\x05Video\x12'\n" +
	"\x0fcontent_version\x18\x01 \x01(\tR\x0econtentVersion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\x05R\x04kind\x12!\n" +
	"\fdownload_url\x18\x05 \x01(\tR\vdownloadUrlB\x1dZ\x1bgpix/pkg/gpmc/gpmcpb;gpmcpbb\x06proto3"

var file_proto_gpmc_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_proto_gpmc_v1_messages_proto_goTypes = []any{
	(*GetUploadTokenRequest)(nil),                    // 0: gpmc.v1.GetUploadTokenRequest
	(*FindRemoteMediaByHashRequest)(nil),             // 1: gpmc.v1.FindRemoteMediaByHashRequest
	(*FindRemoteMediaByHashResponse)(nil),            // 2: gpmc.v1.FindRemoteMediaByHashResponse
	(*UploadReceipt)(nil),                            // 3: gpmc.v1.UploadReceipt
	(*CommitUploadRequest)(nil),                      // 4: gpmc.v1.CommitUploadRequest
	(*CommitUploadResponse)(nil),                     // 5: gpmc.v1.CommitUploadResponse
	(*PrepareDownloadRequest)(nil),                   // 6: gpmc.v1.PrepareDownloadRequest
	(*LibStateRequest)(nil),                          // 7: gpmc.v1.LibStateRequest
	(*LibStateResponse)(nil),                         // 8: gpmc.v1.LibStateResponse
	(*MediaItem)(nil),                                // 9: gpmc.v1.MediaItem
	(*PrepareDownloadResponse)(nil),                  // 10: gpmc.v1.PrepareDownloadResponse
	(*FindRemoteMediaByHashRequest_Inner)(nil),       // 11: gpmc.v1.FindRemoteMediaByHashRequest.Inner
	(*FindRemoteMediaByHashRequest_Inner_Hash)(nil),  // 12: gpmc.v1.FindRemoteMediaByHashRequest.Inner.Hash
	(*FindRemoteMediaByHashRequest_Inner_Empty)(nil), // 13: gpmc.v1.FindRemoteMediaByHashRequest.Inner.Empty
	(*FindRemoteMediaByHashResponse_L1)(nil),         // 14: gpmc.v1.FindRemoteMediaByHashResponse.L1
	(*FindRemoteMediaByHashResponse_L1_L2)(nil),      // 15: gpmc.v1.FindRemoteMediaByHashResponse.L1.L2
	(*FindRemoteMediaByHashResponse_L1_L2_L3)(nil),   // 16: gpmc.v1.FindRemoteMediaByHashResponse.L1.L2.L3
	(*CommitUploadRequest_Inner)(nil),                // 17: gpmc.v1.CommitUploadRequest.Inner
	(*CommitUploadRequest_Device)(nil),               // 18: gpmc.v1.CommitUploadRequest.Device
	(*CommitUploadRequest_Inner_Timestamp)(nil),      // 19: gpmc.v1.CommitUploadRequest.Inner.Timestamp
	(*CommitUploadResponse_L1)(nil),                  // 20: gpmc.v1.CommitUploadResponse.L1
	(*CommitUploadResponse_L1_L3)(nil),               // 21: gpmc.v1.CommitUploadResponse.L1.L3
	(*PrepareDownloadRequest_KeyInner)(nil),          // 22: gpmc.v1.PrepareDownloadRequest.KeyInner
	(*PrepareDownloadRequest_KeyOuter)(nil),          // 23: gpmc.v1.PrepareDownloadRequest.KeyOuter
	(*PrepareDownloadRequest_Empty)(nil),             // 24: gpmc.v1.PrepareDownloadRequest.Empty
	(*PrepareDownloadRequest_OpaqueF1Inner)(nil),     // 25: gpmc.v1.PrepareDownloadRequest.OpaqueF1Inner
	(*PrepareDownloadRequest_OpaqueF1)(nil),          // 26: gpmc.v1.PrepareDownloadRequest.OpaqueF1
	(*PrepareDownloadRequest_OpaqueF5Inner5)(nil),    // 27: gpmc.v1.PrepareDownloadRequest.OpaqueF5Inner5
	(*PrepareDownloadRequest_OpaqueF5)(nil),          // 28: gpmc.v1.PrepareDownloadRequest.OpaqueF5
	(*PrepareDownloadRequest_Opaque)(nil),            // 29: gpmc.v1.PrepareDownloadRequest.Opaque
	(*LibStateRequest_Inner)(nil),                    // 30: gpmc.v1.LibStateRequest.Inner
	(*LibStateResponse_Body)(nil),                    // 31: gpmc.v1.LibStateResponse.Body
	(*MediaItem_Meta)(nil),                           // 32: gpmc.v1.MediaItem.Meta
	(*MediaItem_Trash)(nil),                          // 33: gpmc.v1.MediaItem.Trash
	(*MediaItem_Kind)(nil),                           // 34: gpmc.v1.MediaItem.Kind
	(*MediaItem_Photo)(nil),                          // 35: gpmc.v1.MediaItem.Photo
	(*MediaItem_Video)(nil),                          // 36: gpmc.v1.MediaItem.Video
	(*MediaItem_Meta_Hashes)(nil),                    // 37: gpmc.v1.MediaItem.Meta.Hashes
	(*PrepareDownloadResponse_L1)(nil),               // 38: gpmc.v1.PrepareDownloadResponse.L1
	(*PrepareDownloadResponse_L1_L5)(nil),            // 39: gpmc.v1.PrepareDownloadResponse.L1.L5
	(*PrepareDownloadResponse_L1_L5_Image)(nil),      // 40: gpmc.v1.PrepareDownloadResponse.L1.L5.Image
	(*PrepareDownloadResponse_L1_L5_Video)(nil),      // 41: gpmc.v1.PrepareDownloadResponse.L1.L5.Video
}
var file_proto_gpmc_v1_messages_proto_depIdxs = []int32{
	11, // 0: gpmc.v1.FindRemoteMediaByHashRequest.inner:type_name -> gpmc.v1.FindRemoteMediaByHashRequest.Inner
	14, // 1: gpmc.v1.FindRemoteMediaByHashResponse.l1:type_name -> gpmc.v1.FindRemoteMediaByHashResponse.L1
	17, // 2: gpmc.v1.CommitUploadRequest.inner:type_name -> gpmc.v1.CommitUploadRequest.Inner
	18, // 3: gpmc.v1.CommitUploadRequest.device:type_name -> gpmc.v1.CommitUploadRequest.Device
	20, // 4: gpmc.v1.CommitUploadResponse.l1:type_name -> gpmc.v1.CommitUploadResponse.L1
	23, // 5: gpmc.v1.PrepareDownloadRequest.key:type_name -> gpmc.v1.PrepareDownloadRequest.KeyOuter
	29, // 6: gpmc.v1.PrepareDownloadRequest.opaque:type_name -> gpmc.v1.PrepareDownloadRequest.Opaque
	30, // 7: gpmc.v1.LibStateRequest.inner:type_name -> gpmc.v1.LibStateRequest.Inner
	31, // 8: gpmc.v1.LibStateResponse.body:type_name -> gpmc.v1.LibStateResponse.Body
	32, // 9: gpmc.v1.MediaItem.meta:type_name -> gpmc.v1.MediaItem.Meta
	34, // 10: gpmc.v1.MediaItem.kind:type_name -> gpmc.v1.MediaItem.Kind
	38, // 11: gpmc.v1.PrepareDownloadResponse.l1:type_name -> gpmc.v1.PrepareDownloadResponse.L1
	12, // 12: gpmc.v1.FindRemoteMediaByHashRequest.Inner.hash:type_name -> gpmc.v1.FindRemoteMediaByHashRequest.Inner.Hash
	13, // 13: gpmc.v1.FindRemoteMediaByHashRequest.Inner.marker:type_name -> gpmc.v1.FindRemoteMediaByHashRequest.Inner.Empty
	15, // 14: gpmc.v1.FindRemoteMediaByHashResponse.L1.l2:type_name -> gpmc.v1.FindRemoteMediaByHashResponse.L1.L2
	16, // 15: gpmc.v1.FindRemoteMediaByHashResponse.L1.L2.l3:type_name -> gpmc.v1.FindRemoteMediaByHashResponse.L1.L2.L3
	3,  // 16: gpmc.v1.CommitUploadRequest.Inner.receipt:type_name -> gpmc.v1.UploadReceipt
	19, // 17: gpmc.v1.CommitUploadRequest.Inner.ts:type_name -> gpmc.v1.CommitUploadRequest.Inner.Timestamp
	21, // 18: gpmc.v1.CommitUploadResponse.L1.l3:type_name -> gpmc.v1.CommitUploadResponse.L1.L3
	22, // 19: gpmc.v1.PrepareDownloadRequest.KeyOuter.inner:type_name -> gpmc.v1.PrepareDownloadRequest.KeyInner
	24, // 20: gpmc.v1.PrepareDownloadRequest.OpaqueF1Inner.f2:type_name -> gpmc.v1.PrepareDownloadRequest.Empty
	25, // 21: gpmc.v1.PrepareDownloadRequest.OpaqueF1.f7:type_name -> gpmc.v1.PrepareDownloadRequest.OpaqueF1Inner
	24, // 22: gpmc.v1.PrepareDownloadRequest.OpaqueF5Inner5.f1:type_name -> gpmc.v1.PrepareDownloadRequest.Empty
	24, // 23: gpmc.v1.PrepareDownloadRequest.OpaqueF5.f2:type_name -> gpmc.v1.PrepareDownloadRequest.Empty
	24, // 24: gpmc.v1.PrepareDownloadRequest.OpaqueF5.f3:type_name -> gpmc.v1.PrepareDownloadRequest.Empty
	27, // 25: gpmc.v1.PrepareDownloadRequest.OpaqueF5.f5:type_name -> gpmc.v1.PrepareDownloadRequest.OpaqueF5Inner5
	26, // 26: gpmc.v1.PrepareDownloadRequest.Opaque.f1:type_name -> gpmc.v1.PrepareDownloadRequest.OpaqueF1
	28, // 27: gpmc.v1.PrepareDownloadRequest.Opaque.f5:type_name -> gpmc.v1.PrepareDownloadRequest.OpaqueF5
	9,  // 28: gpmc.v1.LibStateResponse.Body.items:type_name -> gpmc.v1.MediaItem
	37, // 29: gpmc.v1.MediaItem.Meta.hashes:type_name -> gpmc.v1.MediaItem.Meta.Hashes
	33, // 30: gpmc.v1.MediaItem.Meta.trash:type_name -> gpmc.v1.MediaItem.Trash
	35, // 31: gpmc.v1.MediaItem.Kind.photo:type_name -> gpmc.v1.MediaItem.Photo
	36, // 32: gpmc.v1.MediaItem.Kind.video:type_name -> gpmc.v1.MediaItem.Video
	39, // 33: gpmc.v1.PrepareDownloadResponse.L1.l5:type_name -> gpmc.v1.PrepareDownloadResponse.L1.L5
	40, // 34: gpmc.v1.PrepareDownloadResponse.L1.L5.image:type_name -> gpmc.v1.PrepareDownloadResponse.L1.L5.Image
	41, // 35: gpmc.v1.PrepareDownloadResponse.L1.L5.video:type_name -> gpmc.v1.PrepareDownloadResponse.L1.L5.Video
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_proto_gpmc_v1_messages_proto_init() }
func file_proto_gpmc_v1_messages_proto_init() {
	if File_proto_gpmc_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gpmc_v1_messages_proto_rawDesc), len(file_proto_gpmc_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gpmc_v1_messages_proto_goTypes,
		DependencyIndexes: file_proto_gpmc_v1_messages_proto_depIdxs,
		MessageInfos:      file_proto_gpmc_v1_messages_proto_msgTypes,
	}.Build()
	File_proto_gpmc_v1_messages_proto = out.File
	file_proto_gpmc_v1_messages_proto_goTypes = nil
	file_proto_gpmc_v1_messages_proto_depIdxs = nil
}
